### ISSUE TITLE
2017 Kickoff Page

### ISSUE THREAD

**Issue by ellgreen33** [FAMNM/famnm-website#10]
Navbar Location: Events > Kickoff
Page Draft: https://docs.google.com/a/umich.edu/document/d/1tdilD9PoB73wd2Brw7X352uLcPr6gCOZ1--psJ4rfVw/edit?usp=sharing

# Additional information
If possible, it would be nice to embed the teaser youtube video. If that's not possible, take out the "embed" and leave the link. Additionally, the **here** would ideally link to the robotics forums page

**Comment by pcbonnen** [comment]
Embedding is done via HTML, and our site is written in pure HTML. Embedding is certainly possible :) (just look at the front page)
