### ISSUE TITLE
Content Change: Available Resources Page

### ISSUE THREAD

**Issue by moneybags1212** [FAMNM/famnm-website#13]
# Basic information

http://famnm.club/teams/resources.html

**Page Draft**: https://docs.google.com/document/d/1ZhA9MywRRfTbEjp0lzhwC4ehOCDhGAUWETU1wI51nFQ/edit

# Additional information
It currently says "Under Construction". I would like that to be replaced with the stuff in that google drive document. I would like the picture to remain next to the text if possible.

**Comment by pcbonnen** [comment]
I can't leave the picture next to the text on mobile devices, but I can do it for screens with a larger widths.
