### ISSUE TITLE
Deleting Mentor Request Form page/Nav-Bar for it

### ISSUE THREAD

**Issue by moneybags1212** [FAMNM/famnm-website#14]
# Basic information

**Page location**: http://famnm.club/teams/mentor-request.html

**Navbar location**: Affilliated Teams --> Mentor Request Form
**Page Draft**: I'd like it to be removed

# Additional information
We are combining mentor and resource request since they do the same thing currently. So basically just remove the page Mentor Request from the website. Edits to the other page will come later.

**Comment by pcbonnen** [comment]
Will these be split in the future? (i.e. should I leave the page file and remove the navbar link or should I delete the page?)
