### ISSUE TITLE
edit to FAMNM "About" page

### ISSUE THREAD

**Issue by ellgreen33** [FAMNM/famnm-website#20]
http://famnm.club/about/index.html

Change wording on page: 

FAMNM will also act as a collegiate network for both FIRST® Alumni and University of Michigan students who volunteer with and support FIRST® teams. The organization aims to provide professional development opportunities including but not limited to resume critiquing, mock interviews, and corporate recruiting events.

**Comment by ellgreen33** [comment]
(Only edit the second PP, the first paragraph is fine)

**Comment by pcbonnen** [comment]
Resolved in 8796c8d.
