### ISSUE TITLE
Update Content on FRC Kickoff Page

### ISSUE THREAD

**Issue by jack-greenbaum** [FAMNM/famnm-website#23]
http://famnm.club/events/kickoff.html

**Navbar text should be updated to:** FAMMN FRC Kickoff 

**Content of the page should be:**
Large Header: FAMNM FIRST Robotics Kickoff
The FIRST Robotics Competition (FRC) season begins each year in early January with a worldwide kickoff. At this time, the year’s challenge is revealed and teams begin their 6-week design and build season. Kickoffs provide an opportunity for teams to interact with each other, pick up their Kit of Parts, and learn about the game. FAMNM has been hosting a kickoff event on University of Michigan campus since 2015 and it has grown to over 40 teams from the greater Ann Arbor area. In addition to showing the game reveal broadcast, we offer tours of the university’s engineering campus, presentations by inspiring professionals and university faculty, and a mock field setup to help students understand the new game.

Medium Header: Header: 2018 FAMNM FIRST® Robotics Kickoff
University of Michigan - Ann Arbor
Saturday, January 6, 2018
FAMNM is excited to host our third annual FRC Kickoff event! We’re currently in the planning stages of the event, using all of the great feedback we’ve received. Check back closer to the event for more details!

**Comment by jack-greenbaum** [comment]
Pictures that are currently there can stay under the first paragraph.

**Comment by pcbonnen** [comment]
Resolved in a993e9d.
