### ISSUE TITLE
New Page: FAMNM FTC Kickoff

### ISSUE THREAD

**Issue by jack-greenbaum** [FAMNM/famnm-website#24]
**Title:** FAMNM FTC Kickoff
**Navbar:** Events -> FAMNM FTC Kickoff
**Content:**
Large Header: FAMNM FIRST Tech Challenge Kickoff
The FIRST Tech Challenge season begins each year in early September with a worldwide kickoff. At this time, the year’s challenge is revealed and teams begin their design and build season. Kickoffs provide an opportunity for teams to work with each other, brainstorm ideas, learn valuable skills through workshops, and interact with a full FTC game field. 

Medium Header: 2017-2018 FAMNM FIRST Tech Challenge Kickoff
University of Michigan - Ann Arbor
September 9, 2017
FAMNM is excited to host our first ever FTC Kickoff event! If you’re team is interested in attending the event, please fill out this interest survey.
Check back closer to the event for more details!
(embedded video) https://www.youtube.com/watch?v=tNPvKb7-3xE

**Comment by pcbonnen** [comment]
Merged in pull request #32
