### ISSUE TITLE
FAMNM Organizational Structure

### ISSUE THREAD

**Issue by ellgreen33** [FAMNM/famnm-website#25]
http://famnm.club/about/org-structure.html

-->Remove officer list

Project Development
The Project Development committee is responsible for organizing events on campus for FIRST® teams, including our annual Kickoff events, FAMNM Forums, and Rookie Quick Build. Additionally, this committee spearheads new programming for FAMNM as a whole.

Treasury
The Treasury Committee is primarily responsible for creating and maintaining a budget, organizing fundraising events, and finding sponsorship within the University. The committee is also responsible for organizing donations to FIRST® teams, as well as maintaining the FIRST® Scholarship at U of M.

Marketing and Campus Outreach
The Marketing and Campus Outreach Committee is responsible for maintaining and updating social media accounts, recruiting new members, and advertising the organization and its events. This committee is also in charge of planning social events for FAMNM.

Corporate Outreach
Unchanged

**Comment by pcbonnen** [comment]
Resolved in 4bf6a61.
