### ISSUE TITLE
New Page: <Resource Request Form>

### ISSUE THREAD

**Issue by alyc110397** [FAMNM/famnm-website#7]
Tab: Affiliated Teams
Page: Resource Request Form (already exists, 'under construction')

Not quite sure if I'm doing this right, but I made the form that goes on this page. You can get the link [here](https://docs.google.com/a/umich.edu/forms/d/1iCKD0g5BI8DVZ7z2VAg46tlAwbfRgp8TX3w88VtH4oE/edit?usp=sharing), or go into our FAMNM google drive here (FAMNM leadership folder -> committees -> MACO -> website -> team related) and get it. Thanks! Let me know if you have any questions 
alyciaan@umich.edu

**Comment by pcbonnen** [comment]
Added in commit bfaf84e6.
